name: "SDK Tester: run unittests and upload coverage to codecov.io"

on:
  workflow_dispatch:
    inputs:
      gitref:
        type: string
        required: true
        

jobs:
  test-and-codecov:
    runs-on: ubuntu-latest
    env:
      OS: linux
      PYTHON: '3.8'
    steps:
    - name: checkout the repo 
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.gitref }}
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Run test and generate coverage report
      working-directory: .
      run: |
        echo "codecov.dev" > VERSION
        make test
