name: "SDK Publisher: upload HTML version API documentation, PyPI distribution"

on: 
  workflow_call:
  push:
    tags: '*'
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      OS: linux
      PYTHON: '3.8'
    steps:
    - name: set package metadata
      run: |
        echo "VERSION=$(echo "${{ github.ref }}" | cut -d/ -f3)" >> $GITHUB_ENV
        echo "PACKAGE=$(echo "${{ github.repository }}" | cut -d/ -f2)" >> $GITHUB_ENV 
    - name: checkout the repo 
      uses: actions/checkout@v3
      with:
        ref: ${{ env.VERSION }}
        fetch-depth: 0
    - name: check clone stat
      run: |
        ls $(pwd) 
        ls clams/develop/templates/github/*
        python -c 'import setuptools ; print(setuptools.version.__version__)'

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: build a sdist
      run: |
        echo ${{ env.VERSION }} > VERSION
        make package
